### ISSUE TITLE
Audiences are represented as string if claims.Set is used

### ISSUE THREAD

**Issue by TimoGatta** [pascaldekloe/jwt#12]
Hi, 
at first, thank you for this awesome library!
But whenever I use `claims.Set = map[string]interface{}{"role": "userrole",}` audiences are stated as a string instead of an array.

E.g.:
```
{
  "aud": "audience.org",
  "exp": 1897992150.1938002,
  "iat": 1582275750,
  "iss": "issuer.org",
  "role": "userrole",
  "sub": "0ff88b48-231c-4862-8fcf-56c7fce32400"
}
```

vs.

```
{
  "aud": [
           "audience.org"
         ],
  "exp": 1897992150.1938002,
  "iat": 1582275750,
  "iss": "issuer.org",
  "sub": "0ff88b48-231c-4862-8fcf-56c7fce32400"
}
```

**Comment by pascaldekloe** [comment]
Thanks for the kind words Timo. :-)

The JWT specification allows for this  optimization explicitly in cases where there is only one audience string. I could make it consistent without the map at some performance cost.

Did you run in trouble with this representation, or is the issue more a precautious concern?

**Comment by pascaldekloe** [comment]
> "In the special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive string containing a StringOrURI value."
https://tools.ietf.org/html/rfc7519#section-4.1.3

**Comment by TimoGatta** [comment]
Thank you for the quick response. If it complies with the standard, then it shouldn't be a problem. I was just wondering, that the datatype changes to a string after setting a custom claim.

**Comment by pascaldekloe** [comment]
The behaviour is inconsistent and not what you'd expect. All this to save 2 + ⅓ byte. 🤨
