### ISSUE TITLE
Feature/example request

### ISSUE THREAD

**Issue by elgs** [pascaldekloe/jwt#14]
This library looks very promising, however, to make it really useful, I have two questions:
1. can you provide a convenient method to convert a JSON string into the jwt.Claims structure?
2. how can I verify a jwt token if I have a private string typed password?

For 1, you can argue that it's not this project's responsibility to do it, that's fine. But for 2, I cannot believe it's not documented in the readme.md. This is the most fundamental use of jwt. I think if your project is better documented, this project will gain 50x more popularity. I have been here several times and was turned off by lacking of useful examples every time. This time I finally decided to open this ticket. Thanks.

**Comment by pascaldekloe** [comment]
1. `err := json.Unmarshal([]byte(myJSON), claims.Set)`
2. `s, ok := claims.String("password")`
Did you actually read the Claims example? 😉

**Comment by elgs** [comment]
Thanks for the example code.

No, I didn't read the Claims example because till now I still have no idea where they are located. My point is these fundamental examples should be in readme.md.

**Comment by pascaldekloe** [comment]
README provides a quick run through to get the picture. Not everyone uses private claims. There's godoc (with examples) for development, and they are ment to be used.

**Comment by elgs** [comment]
Totally understand. Thanks!

There are two types of people:

1. if there's example in the code, why would I bother to write them in README.md;
2. if I could put examples in README.md, why would I bother users to read the code;

I fully respect each of the styles. So it's fine to keep the examples in the code. Thank you so much!

**Comment by pascaldekloe** [comment]
No need for reading code either. Just use godoc.
https://godoc.org/github.com/pascaldekloe/jwt#example-Claims--ByName
