### ISSUE TITLE
why claims.HMACSign returned token is base64 encoded?

### ISSUE THREAD

**Issue by laeo** [pascaldekloe/jwt#15]
Sorry for this, but i really don't know why we had to encoding it, hoping someone can explain for me, thanks.

**Comment by laeo** [comment]
OK i got the answer, i must convert byte slice to string, or not `muxie.Dispatch` will do a base64 encoding automatically. Sorry for my foolish.

**Comment by pascaldekloe** [comment]
Hi Laeo, the JWT tokens are supposed to be 3 base64 parts, combinend together with two dots. The Check methods decode again (to Claims).

**Comment by pascaldekloe** [comment]
Ment to tag issue #17 with the commit above. ☝️
