### ISSUE TITLE
claims.Set int entries are treated as float64

### ISSUE THREAD

**Issue by tapir** [pascaldekloe/jwt#2]
So I'm setting some integer values in Set, and when I receive back the JWT and decode it they are treated as float64 so when I do `c.Set["something"].(int)` the compiler complains about `Panic caught: interface conversion: interface {} is float64, not int`

**Comment by pascaldekloe** [comment]
In JavaScript *all* numbers are float64. Use Go's `ok` boolean for safe conversion.

```go
if f, ok := c.Set["something"].(float64); ok {
        something = int(f)
}
```

… or with the JWT API:

```go
if f, ok := c.Number("something"); ok {
        something = int(f)
}
