### ISSUE TITLE
Use semver to support go module

### ISSUE THREAD

**Issue by jammehcow** [pascaldekloe/jwt#3]
If you try to use this lib with go 1.11's module system the latest release it will download is v1.2.1. Go modules require tags to be formatted as ``vx.y.z`` where x is MAJOR, y is MINOR and z is the PATCH number. Could you migrate tags and releases to semver-formatted strings?

**Comment by jammehcow** [comment]
https://github.com/golang/go/wiki/Modules#semantic-import-versioning

**Comment by pascaldekloe** [comment]
Sure, I'll double tag'm on Monday.

**Comment by pascaldekloe** [comment]
Done. Thanks for the detailed report @jammehcow.
