### ISSUE TITLE
My project's tests are failing due to jwt's import paths

### ISSUE THREAD

**Issue by thecsw** [pascaldekloe/jwt#4]
Hey there! Love your package. It's very simple and straight-forward. I prefer it to other JWT packages thanks to its API. Great job!

I only have one problem. I have jwt in my project and it's in my `go.mod` and in `go.sum`. Every time I try to run `go test -v -count=1 ./...` in my root directory, it complains about `jwt`'s imported library and fails:

``` sh
myproject:master* λ go test -v -count=1 ./...
../../pascaldekloe/jwt/check.go:6:2: cannot find package "crypto/ed25519" in any of:
	/usr/lib/go/src/crypto/ed25519 (from $GOROOT)
	/home/myusername/go/src/crypto/ed25519 (from $GOPATH)
```

`crypto/ed25519` exists on my system:

``` sh
ed25519:master λ pwd
/home/myusername/go/src/golang.org/x/crypto/ed25519
```

Is there something wrong with my system variables or import paths? 

This problem doesn't occur with any other packages.

Thanks!

**Comment by pascaldekloe** [comment]
Thanks for the kind words Sandy, I'm glad to hear you like it. ☺️

The current HEAD uses a new package `crypto/ed25519` from the following Go 1.13 release.

In the meantime you could use a tagged release. The latest is version 1.5.0. `Go.mod` is there to help. Please let me know if you could use some pointers.

**Comment by thecsw** [comment]
@pascaldekloe Living on bleeding edge? Even arch doesn’t have 1.13 yet. Thank for the reply!

**Comment by pascaldekloe** [comment]
Indeed. 😄 I was curious about the EdDSA performance, and things look good. Highly recommended. The version 1.6.0 tag will wait on the release day of Go 1.13.

You can download a beta at https://golang.org/dl b.t.w..

**Comment by thecsw** [comment]
Great stuff!

**Comment by pascaldekloe** [comment]
@milQA made a fork for older Go versions at https://github.com/milQA/jwt1 b.t.w.

**Comment by milQA** [comment]
Yes, I also had a problem with the import and I solved it this way.
😂
