### ISSUE TITLE
Remove goe dependency

### ISSUE THREAD

**Issue by alexedwards** [pascaldekloe/jwt#5]
Thanks for your work on this package.

In the README it says the package uses no third-party dependencies, but the `go.mod` file lists the dependency `github.com/pascaldekloe/goe`.

From a quick check it looks like the only place `goe` is being used is the following line: https://github.com/pascaldekloe/jwt/blob/fcba0b3ef7ede11014a95c26e2ecea73a94e5013/x/x_test.go#L134 

I was wondering if the test could be refactored to inline any necessary code, instead of pulling through the whole dependency?

**Comment by pascaldekloe** [comment]
Go modules does not distinguish between test and runtime dependencies. An unfortunate choice for those who care.

The experimental JWK seems to work. Time to promote it to the main package. There just a bit of work pending to reach full test coverage. Let's eliminate that dependency while we're at it indeed.

**Comment by alexedwards** [comment]
Great, thank you :smile:

**Comment by pascaldekloe** [comment]
Related to golang/go#26955.
