### ISSUE TITLE
How to encode/decode ed25519 keys

### ISSUE THREAD

**Issue by davisford** [pascaldekloe/jwt#6]
Must these be stored in binary in a file?  I want to persist them to a file, but so far have not been able to encode/decode as PEM, or even base64.  They are always corrupt when I read them back in.

If I try to generate the keys from `openssl` or `ssh-keygen`, I'm also not able to read those in as valid ed25519 keys.  

The test I use is to generate them in Go, then try to encode them, decode them, and re-run a sign/verify.

**Comment by pascaldekloe** [comment]
The issue is unrelated to this JWT library.

Both `ed25519.PrivateKey` and `ed25519.PublicKey` are a `[]byte`! What could be easier to store?

There's even a jwt.KeyRegister.LoadPEM to read keys from ssh-keygen(1), openssl(1).

**Comment by davisford** [comment]
Yep, I can store them as binary.  My question was really more if there is a standard text `pem` or other... format that they can be converted to and read back in.  So far, the answer AFAIK is no.

**Comment by pascaldekloe** [comment]
PEM is the defacto standard, and KeyRegister supports it fully.
